version: 2

sources:
  - name: chessprompter
    schema: main
    description: Raw star schema tables created by the chessprompter Python CLI
    tables:
      - name: fact_games
        description: Central fact table — one row per chess game
      - name: dim_player
        description: Player dimension — unique players
      - name: dim_date
        description: Date dimension — game dates
      - name: dim_event
        description: Event dimension — tournament/match info
      - name: dim_result
        description: Result dimension — game outcomes (1-0, 0-1, 1/2-1/2)
      - name: game_players
        description: Junction table for consultation games with multiple players per side
