name: chessprompter_dbt
version: "1.0.0"

profile: chessprompter_dbt

model-paths: ["models"]

models:
  chessprompter_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
