version: 2

models:
  - name: player_stats
    description: Win/loss/draw statistics aggregated per player
    columns:
      - name: player
        description: Player display name
        data_tests:
          - unique
          - not_null

  - name: opening_stats
    description: Game statistics aggregated by ECO opening code
    columns:
      - name: eco
        description: ECO opening code
        data_tests:
          - unique
          - not_null
